# --------------------
# Base
# --------------------
# Homebrew
tap "homebrew/services"

# --------------------
# Mac Tools
# --------------------
# Browser
cask "brave-browser"
cask "google-chrome"

# IME
cask "google-japanese-ime"

# Mounty
cask "macfuse"
tap "gromgit/homebrew-fuse"
brew "ntfs-3g-mac"
cask "gromgit/fuse/mounty"

# Inbox
cask "raycast"
cask "scroll-reverser"
cask "deepl"
cask "appcleaner"
cask "iina"
cask "notunes"

# --------------------
# Dev Tools
# --------------------
# Ruby
brew "icu4c"
brew "libyaml"
brew "openssl@3"
brew "openssl@1.1"
brew "rbenv"
brew "readline"
brew "ruby-build"

# Node.js
brew "nodenv"
brew "node-build"
brew "node"
brew "yarn"
brew "npm"

# Python
brew "python"

# Java
brew "openjdk"

# Go
brew "goenv"

# Editor
cask "visual-studio-code"
cask "cursor"
brew "nvim"

# Terminal
cask "iterm2"
cask "warp"

# API Client
cask "postman"

# DB Client
cask "dbeaver-community"

# DB
brew "mysql"
brew "postgresql@14"
brew "sqlite"

# Docker
cask "docker"

# Kubernetes
brew "minikube"
brew "hyperkit"
brew "kind"
brew "kubernetes-cli"

# VPN
cask "tunnelblick"
brew "openvpn"

# Font
tap 'homebrew/cask-fonts'
cask 'font-hackgen'
cask 'font-hackgen-nerd'

# AWS
brew "awscli"

# Scrcpy
brew "scrcpy"
cask "android-platform-tools"

# Fastly
tap "fastly/tap"
brew "fastly/tap/fastly"

# terraform
brew "tfenv"

# Testing
brew "jmeter"

# Mutagen
tap "mutagen-io/mutagen"
brew "mutagen-io/mutagen/mutagen-compose"

# Command line tools
brew "direnv"
brew "jq"
brew "mas"
brew "telnet"
brew "yamllint"
brew "tree"
brew "wget"
brew "just"

# Inbox
brew "gcc"
brew "guile"
brew "gnupg"
brew "gnutls"
brew "gmp"
brew "graphviz"
brew "coreutils"
brew "redis"
brew "ansible"

# --------------------
# Work Tools
# --------------------
# Message
cask "slack"
