# credential
brew "direnv"

# cli
brew "awscli"

# package manager
brew "yarn"
brew "mas"

# editor
brew "nvim"

# ruby
brew "icu4c"
brew "libyaml"
brew "openssl@3"
brew "rbenv"
brew "readline"
brew "ruby-build"

# python
brew "python@3.11"

# node
brew "node"
brew "nvm"

# db
brew "mysql"
brew "postgresql@14"
brew "sqlite"

# iac
brew "terraform"

# launcher
cask "raycast"

# file system
cask "mounty"

# android
brew "scrcpy"
cask "android-platform-tools"

# other
brew "gcc"
brew "guile"
brew "gnupg"
brew "gnutls"
brew "gmp"
brew "jq"
brew "nginx"
brew "pandoc"
brew "telnet"
brew "tree"
brew "wget"
